### PR TITLE
Refactored view query_viewmodel and class Counter

### PR DESCRIPTION
**Pull request by guilhermemaba**
Hello @chrisclark ,

I liked this project. Congratulations!
I rewrote small part of the code.

Regards

### CODE REVIEW

**Comment by chrisclark** [comment]
Hi @guilhermemaba -- thanks for the kind words and the nice refactor. I just merged in a good-size branch that now causes a merge conflict with this PR. Can you rebase from master and I can merge the PR? Thanks!

**Comment by guilhermemaba** [comment]
@chrisclark thanks too!
I pulled in my master branch, sorry.
Do you prefer rebase?

**Comment by chrisclark** [comment]
Afraid I can't merge this; it's missing the 'bucket' and 'snapshot' params in the viewmodel. This does, however, expose a weakness in the test suite which I need to address. If you can fix that up, I will get it merged. Thanks again!

**Comment by guilhermemaba** [comment]
It's correct?

**Comment by chrisclark** [comment]
I'm sorry man -- I can't merge this. It seems like the counter refactor just removes some safety (the is not None check was there for a reason) and using settings.EXPLORER_S3_BUCKET instead of app_settings is wrong. Even if those issues are fixed, there just isn't significant gains here and it's exhibited enough problems that I don't want to merge it. I really appreciate the effort, but I'm not going to take the PR.

**Pull request closed without merging**
