### PR TITLE
Added support for Python 2.6 with a custom counter class from the Intern...

### PR DESCRIPTION
**Pull request by rodvdka**
...et with no license restrictions and a small change to views.py

Counter.py is from http://code.activestate.com/recipes/576611-counter-class/ with an MIT License.

This should make it run without any issues on Python 2.6.

### CODE REVIEW

**Comment by sindrig** [comment]
I did a similar thing before seeing this pull request.

**Comment by chrisclark** [comment]
Sounds like there is appetite for this. And @rodvdka I'm sorry for ignoring this for so long.

Could you strip down the counter class so it looks more like this?

https://github.com/epantry/django-sql-explorer/compare/compat-26

I hate having so much dead and untested code hanging around. I can just merge that branch as well, but I'd love to give you credit for the contribution.

**Comment by rodvdka** [comment]
Thanks, I'll do it tomorrow at work.

**Comment by chrisclark** [comment]
Let me know if you want me to do it as well. I can still add you to the contributors file :)

**Comment by rodvdka** [comment]
Please confirm this commit now. Thanks @chrisclark

**Comment by chrisclark** [comment]
0.7 has just been released which includes this change. Thanks for the help!

**Pull request merged**
